# STAGE 1
FROM eclipse-temurin:17-alpine as jre-build

WORKDIR /minecraft
RUN mkdir mods
RUN echo 'eula=true' > eula.txt

# Copy scripts and jar files
COPY ./fabric-server-mc.1.20.4-loader.0.15.9-launcher.1.0.0.jar /minecraft

# Get jar file dependencies
RUN jar xf fabric-server-mc.1.20.4-loader.0.15.9-launcher.1.0.0.jar
RUN rm -f modules.txt
RUN touch modules.txt

RUN jdeps \
    --ignore-missing-deps \
    --print-module-deps \
    --recursive \
    --class-path "BOOT-INF/lib/*" \
    fabric-server-mc.1.20.4-loader.0.15.9-launcher.1.0.0.jar > modules.txt

# Create a custom Java runtime
RUN $JAVA_HOME/bin/jlink \
    --add-modules java.base,java.logging \
    --strip-debug \
    --no-man-pages \
    --no-header-files \
    --compress=2 \
    --output /javaruntime

# STAGE 2 
FROM alpine:3.19
WORKDIR /minecraft
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"

COPY ./start.sh /minecraft
COPY ./lithium-fabric-mc1.20.4-0.12.1.jar /minecraft/mods
COPY ./fabric-server-mc.1.20.4-loader.0.15.9-launcher.1.0.0.jar /minecraft
COPY ./fabric-installer-1.0.0.jar /minecraft
COPY --from=jre-build /javaruntime $JAVA_HOME

EXPOSE 25565

ENTRYPOINT ["sh"]